"""
Helpers for locating and loading tension measurement results.

The repository currently has two result formats/locations in circulation:

- Legacy single file: ``stencil_tension_measurements.json``
- Current orchestrator output: ``tension_routines/tension_measurement_*.json``

These helpers provide one place to resolve the latest usable data for
controllers and dialogs.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Optional


LEGACY_MEASUREMENT_FILE = "stencil_tension_measurements.json"
TENSION_ROUTINES_DIR = "tension_routines"
TENSION_ROUTINES_PATTERN = "tension_measurement_*.json"


def _extract_session_from_dialog(tension_dialog: Optional[Any]) -> Optional[dict]:
    """Return in-memory session data from the dialog when available."""
    if tension_dialog is None:
        return None

    orchestrator = getattr(tension_dialog, "orchestrator", None)
    session = getattr(orchestrator, "session", None)
    if session is None:
        return None

    measurements = getattr(session, "measurements", None)
    if not measurements:
        return None

    return session.to_dict()


def find_latest_tension_measurement_file(base_path: Optional[Path] = None) -> Optional[Path]:
    """Locate the most recent persisted tension measurement file."""
    root = Path(base_path) if base_path is not None else Path.cwd()

    legacy_file = root / LEGACY_MEASUREMENT_FILE
    if legacy_file.exists():
        return legacy_file

    routines_dir = root / TENSION_ROUTINES_DIR
    if not routines_dir.exists():
        return None

    candidates = sorted(
        routines_dir.glob(TENSION_ROUTINES_PATTERN),
        key=lambda path: (path.stat().st_mtime, path.name),
        reverse=True,
    )
    return candidates[0] if candidates else None


def load_tension_measurement_data(
    tension_dialog: Optional[Any] = None,
    base_path: Optional[Path] = None,
) -> dict:
    """
    Load tension measurement data from the most relevant available source.

    Resolution order:
    1. In-memory session attached to the measurement dialog
    2. Legacy fixed JSON file in repository root
    3. Latest JSON generated by the measurement orchestrator
    """
    session_data = _extract_session_from_dialog(tension_dialog)
    if session_data is not None:
        return session_data

    measurement_file = find_latest_tension_measurement_file(base_path)
    if measurement_file is None:
        raise FileNotFoundError("Nenhum arquivo de medicao de tensao encontrado")

    with open(measurement_file, "r", encoding="utf-8") as stream:
        return json.load(stream)
