from __future__ import annotations

from typing import List, Tuple

from .parser import GerberObject


def _mm_to_coord(
    v_mm: float,
    fmt_int: int = 3,
    fmt_dec: int = 3,
) -> str:
    """
    Converte um valor em mm para string de coordenada Gerber,
    usando formato FSLAX{fmt_int}{fmt_dec}Y{fmt_int}{fmt_dec}.

    Ex.: fmt_int=3, fmt_dec=3 → 12.345 mm → "012345"
    """
    scale = 10 ** fmt_dec
    val = int(round(v_mm * scale))
    sign = "-" if val < 0 else ""
    val = abs(val)
    total_len = fmt_int + fmt_dec
    s = f"{val:0{total_len}d}"
    return sign + s


def objects_to_gerber(
    objects: List[GerberObject],
    fmt_int: int = 3,
    fmt_dec: int = 3,
) -> List[str]:
    """
    Gera um arquivo Gerber RS-274X mínimo a partir da lista de objetos
    (GerberObject), convertendo **todos** em regiões sólidas (G36/G37).

    Simplificações:
      - Unidade fixa em milímetros (%MOMM*%).
      - Formato fixo FSLAX33Y33 por padrão (3 inteiros, 3 decimais).
      - Não há uso de aperturas (%ADD...), tudo é região.
    """
    lines: List[str] = []

    # Cabeçalho mínimo
    lines.append("G04 Generated by GerberMacroViewer*")
    lines.append(f"%FSLAX{fmt_int}{fmt_dec}Y{fmt_int}{fmt_dec}*%")
    lines.append("%MOMM*%")
    lines.append("%LPD*%")  # Layer polarity: Dark

    for obj in objects:
        poly = obj.polygon_mm
        if not poly or len(poly) < 3:
            continue

        # Remove ponto final duplicado, se for igual ao inicial
        pts: List[Tuple[float, float]] = poly
        if len(pts) >= 2 and pts[0] == pts[-1]:
            pts = pts[:-1]
        if len(pts) < 3:
            continue

        # Região
        lines.append("G36*")

        # Move (D02) para o primeiro ponto
        x0, y0 = pts[0]
        xs = _mm_to_coord(x0, fmt_int, fmt_dec)
        ys = _mm_to_coord(y0, fmt_int, fmt_dec)
        lines.append(f"X{xs}Y{ys}D02*")

        # Interpola (D01) pelos demais pontos
        for x, y in pts[1:]:
            xs = _mm_to_coord(x, fmt_int, fmt_dec)
            ys = _mm_to_coord(y, fmt_int, fmt_dec)
            lines.append(f"X{xs}Y{ys}D01*")

        lines.append("G37*")

    # Fim de arquivo
    lines.append("M02*")

    # Garante quebra de linha em cada linha
    out = [ln if ln.endswith("\n") else ln + "\n" for ln in lines]
    return out